name: continuous-integration
on:
  workflow_call:
    inputs:
      role-to-assume:
        default: false
        description: "Role to assume on AWS"
        required: true
        type: string
      app:
        default: false
        description: "app to build"
        required: true
        type: string
      region:
        default: "us-east-1"
        required: false
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Git Checkout
        uses: actions/checkout@v3
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.region }}
      - 
        name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"
      - 
        # This step needs to give Read and Write permissions to GITHUB_TOKEN when running workflows in this repository
        name: Create new Repo Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and Push to AWS ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker buildx build --push --platform linux/amd64 \
          --tag ${{ env.REGISTRY }}/${{ inputs.app }}:${{ steps.tag_version.outputs.new_tag }} .
      - 
        name: Build and Push to AWS ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker buildx build --push --platform linux/amd64 \
          --tag ${{ env.REGISTRY }}/${{ inputs.app }}:${{ steps.tag_version.outputs.new_tag }} .

# TODO - Create bump-image Job
